name: Build RPM and DEB Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm build-essential fakeroot dpkg-dev
        sudo apt-get install gcc make

    - name: Set up RPM build directories
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

    - name: Copy files to RPM build directories
      run: |
        cp script_caunter.sh ~/rpmbuild/SOURCES/script_caunter.sh
        cp lab6/rpm/SPECS/script_caunter.spec ~/rpmbuild/SPECS/script_caunter.spec
        
    - name: Check gcc and make availability
      run: |
        gcc --version
        make --version
    

    - name: Build RPM package
      run: |
        rpmbuild -ba ~/rpmbuild/SPECS/script_caunter.spec

    - name: Set up DEB build directory structure
      run: |
        mkdir -p ~/debbuild/script-caunter-1.0/usr/local/bin
        mkdir -p ~/debbuild/script-caunter-1.0/usr/share/doc/script-caunter
        mkdir -p ~/debbuild/script-caunter-1.0/DEBIAN

        cp script_caunter.sh ~/debbuild/script-caunter-1.0/usr/local/bin/
        cp lab6/deb/DEBIAN/control ~/debbuild/script-caunter-1.0/DEBIAN/control
        cp lab6/deb/DEBIAN/rules ~/debbuild/script-caunter-1.0/DEBIAN/rules
        cp lab6/deb/DEBIAN/compat ~/debbuild/script-caunter-1.0/DEBIAN/compat

    - name: Build DEB package
      run: |
        cd ~/debbuild/script-caunter-1.0
        dpkg-deb --build . ../script-caunter-1.0.deb

    - name: Upload RPM and DEB artifacts
      uses: actions/upload-artifact@v3
      with:
        name: script_caunter_package
        path: |
          ~/rpmbuild/RPMS/noarch/script_caunter-1.0-1.noarch.rpm
          ~/debbuild/script-caunter-1.0.deb
