name: Build RPM and DEB Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
          sudo apt-get update
          sudo apt-get install -y rpm build-essential fakeroot dpkg-dev

    - name: Create necessary directories for DEB and RPM
      run: |
        mkdir -p lab6/deb/bin
        mkdir -p lab6/rpm/SOURCES
        echo "Directories created"

    - name: List files before copying for debugging
      run: ls -R

    - name: Copy script_caunter.sh to RPM sources
      run: cp ./script_caunter.sh ./lab6/rpm/SOURCES/

    - name: List files after copying to RPM
      run: ls -R ./lab6/rpm/SOURCES/

    - name: Prepare DEB sources
      run: cp ./script_caunter.sh ./lab6/deb/bin/

    - name: List files after copying to DEB
      run: ls -R ./lab6/deb

    - name: Build DEB package
      run: dpkg-deb --build lab6/deb

    - name: Check gcc and make availability
      run: |
        gcc --version
        make --version

    - name: Build RPM package
      run: rpmbuild -bb lab6/rpm/SPECS/script_caunter.spec

    - name: List generated packages
      run: |
        ls -R lab6/deb
        ls -R lab6/rpm
