name: Build RPM and DEB Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up RPM build environment
      run: sudo apt-get update && sudo apt-get install -y rpm

    - name: Build RPM package
      run: |
        cp "lab6(rpm and deb)/script_caunter.spec" ~/rpmbuild/SPECS/
        cp "lab6(rpm and deb)/script_caunter.sh" ~/rpmbuild/SOURCES/
        rpmbuild -ba ~/rpmbuild/SPECS/script_caunter.spec
        cp ~/rpmbuild/RPMS/**/*.rpm "lab6(rpm and deb)/results/"

    - name: Upload RPM artifact
      uses: actions/upload-artifact@v4
      with:
        name: script-caunter-rpm
        path: "lab6(rpm and deb)/results/*.rpm"

    - name: Set up DEB build environment
      run: sudo apt-get install -y dpkg-dev

    - name: Build DEB package
      run: |
        cp "lab6(rpm and deb)/control" ~/debbuild/DEBIAN/
        cp "lab6(rpm and deb)/script_caunter.sh" ~/debbuild/usr/local/bin/
        dpkg-deb --build ~/debbuild
        cp ~/debbuild.deb "lab6(rpm and deb)/results/script-caunter_1.0_all.deb"

    - name: Upload DEB artifact
      uses: actions/upload-artifact@v4
      with:
        name: script-caunter-deb
        path: "lab6(rpm and deb)/results/*.deb"
