name: Build RPM and DEB Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y rpm dpkg-dev
      
    - name: Prepare RPM sources
      run: cp script_caunter.sh lab6/

    - name: Build RPM package
      run: |
        rpmbuild -bb \
          --define "_topdir $(pwd)/lab6" \
          --define "_rpmdir $(pwd)/lab6/results" \
          --define "_srcrpmdir $(pwd)/lab6/results" \
          --define "_specdir $(pwd)/lab6" \
          --define "_sourcedir $(pwd)/lab6" \
          --nocheck \
          lab6/script_caunter.spec

    - name: Upload RPM artifact
      uses: actions/upload-artifact@v4
      with:
        name: script-caunter-rpm
        path: "lab6/results/*.rpm"

    - name: Build DEB package
      run: |
        mkdir -p lab6/results/DEBIAN
        cp lab6/control lab6/results/DEBIAN/
        cp script_caunter.sh lab6/results/usr/local/bin/
        dpkg-deb --build lab6/results
        mv lab6/results.deb lab6/results/script-caunter_1.0_all.deb

    - name: Upload DEB artifact
      uses: actions/upload-artifact@v4
      with:
        name: script-caunter-deb
        path: "lab6/results/*.deb"
