name: Build RPM and DEB Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y rpm dpkg-dev
      
    - name: Create necessary directories for DEB and RPM
      run: |
        mkdir -p lab6/deb/bin
        mkdir -p lab6/rpm/SOURCES
      
    - name: Prepare DEB sources
      run: cp script_caunter.sh lab6/deb/bin
      
    - name: Prepare RPM sources
      run: cp script_caunter.sh lab6/rpm/SOURCES

    
