name: Build RPM and DEB Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up RPM build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm

    - name: Build RPM package
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cp script_caunter.sh ~/rpmbuild/SOURCES/
        cp script_caunter.spec ~/rpmbuild/SPECS/
        rpmbuild -ba ~/rpmbuild/SPECS/script_caunter.spec

    - name: Upload RPM artifact
      uses: actions/upload-artifact@v2
      with:
        name: script-caunter-rpm
        path: ~/rpmbuild/RPMS/**/*.rpm

    - name: Set up DEB build environment
      run: sudo apt-get install -y dpkg-dev

    - name: Build DEB package
      run: |
        mkdir -p ~/debbuild/DEBIAN
        cp control ~/debbuild/DEBIAN/
        mkdir -p ~/debbuild/usr/local/bin
        cp script_caunter.sh ~/debbuild/usr/local/bin/
        dpkg-deb --build ~/debbuild

    - name: Upload DEB artifact
      uses: actions/upload-artifact@v2
      with:
        name: script-caunter-deb
        path: ~/debbuild.deb